development:
    adapter: postgresql
    database: financial_devel
    username: postgres
    password: postgres
    host: localhost

# Banco de teste. Nao confie em salvar nada aqui
test:
    adapter: postgresql
    database: financial_test
    username: postgres
    password: postgres
    host: 127.0.0.1

production:
    adapter: postgresql
    database: financial_prod
    username: postgres
    password: postgres
    host: localhost
